version: 2.1
jobs:
  lp-build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: lp-dependency-cache-{{ checksum "pom.xml" }}
      - run: 
          name: Setup VM and Build
          command: bash vmsetup.sh
          
      - run: find . -type f -name "jacoco.xml" -exec bash -c 'dir=$(basename $(dirname $(dirname $(dirname $(dirname $0))))); mkdir -p /tmp/reports/$dir; cp $0 /tmp/reports/$dir' {} \;
      
      - store_artifacts:
          path: /tmp/coverage_reports
          destination: coverage_reports
      
      - run:
          name: Download codacy coverage jar file.
          command: wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets[0].browser_download_url')

      - run:
          name: Push coverage report to Codacy - Partial
          command: find . -name jacoco.xml | awk '{print "java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r " $0 " --partial"}' | bash

      - run:
          name: Push coverage report to Codacy - Final
          command: java -jar ~/codacy-coverage-reporter-assembly-latest.jar final

      - save_cache:
          key: lp-dependency-cache-{{ checksum "pom.xml" }}
          paths: ~/.m2
          
     
        
workflows:
  version: 2.1
  workflow:
    jobs:
      - lp-build
